"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-8&ar7635wwt_nzoz#)3eh&97!v=birf-g7^f+b+8_#m#(f#-72')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'hotel-management-backend-nu99.onrender.com',
    os.environ.get('PYTHONANYWHERE_HOST', ''),
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'myapp',
    
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'https://localhost:3000',
    os.environ.get('FRONTEND_URL', 'http://localhost:3000'),
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",  # allow all Vercel preview/production URLs
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'https://localhost:3000',
    os.environ.get('FRONTEND_URL', 'http://localhost:3000'),
    'https://hotel-management-backend-nu99.onrender.com',
]

CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'




# Database — Supabase in production, SQLite locally
# import os
# import dj_database_url
# from django.core.exceptions import ImproperlyConfigured
# from django.db import connections

# _db_url = os.environ.get("postgresql://postgres:[depmiv-9wybsi-ceQror]@db.spoiumopdhwqmcxytfkc.supabase.co:5432/postgres")

# if not _db_url:
#     raise ImproperlyConfigured(
#         "DATABASE_URL is not set. Supabase/Postgres connection is required."
#     )

# DATABASES = {
#     "default": dj_database_url.parse(
#         _db_url,
#         conn_max_age=600,
#         ssl_require=True,
#     )
# }

# try:
#     connections["default"].cursor()
#     print("✅ Database connected successfully")
# except Exception as e:
#     raise ImproperlyConfigured(f"❌ Database connection failed: {e}")



import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.db import connections

_db_url = os.environ.get("DATABASE_URL")

if not _db_url:
    raise ImproperlyConfigured(
        "❌ DATABASE_URL is not set. Supabase/Postgres connection required."
    )

DATABASES = {
    "default": dj_database_url.parse(
        _db_url,
        conn_max_age=600,
        ssl_require=True,
    )
}

try:
    connections["default"].cursor()
    print("✅ Database connected successfully")
except Exception as e:
    raise ImproperlyConfigured(f"❌ Database connection failed: {e}")




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SESSION_ENGINE = 'django.contrib.sessions.backends.db'

SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days in seconds

SESSION_COOKIE_SECURE = True
SESSION_SAVE_EVERY_REQUEST = True

# Ensure sessions are persistent (not expiring when the browser is closed)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False



AUTH_USER_MODEL = "myapp.User" 
APPEND_SLASH = False




MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sijanofficial1@gmail.com'
EMAIL_HOST_PASSWORD = 'ktxm ggvn bqpk ujay'

# Field encryption key for PaymentGatewayConfig and OTAChannelConfig
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Set this in your environment or .env file — never commit the real key
import os

# Khalti fallback key — used when a hotel hasn't configured their own Khalti credentials yet
# Hotels override this via Settings → Payment & OTA.
KHALTI_SECRET_KEY = os.environ.get('KHALTI_SECRET_KEY', '2f2766ead6dd4866ac3b0ce0be469801')

FIELD_ENCRYPTION_KEY = os.environ.get(
    'FIELD_ENCRYPTION_KEY',
    'Jz5oW6gqBNEqoVl14BDGSj5H6u4YI36jUOiG7eEsGms='  # dev only — set FIELD_ENCRYPTION_KEY env var in production
)


