# Generated by Django 6.0.2 on 2026-03-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hotel',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
