# Generated by Django 6.0.3 on 2026-04-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTAChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('platform_type', models.CharField(choices=[('channel_manager', 'Channel Manager'), ('ota', 'OTA')], max_length=20)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField(blank=True)),
                ('extra_config', models.TextField(blank=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hotel', 'platform_name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_type', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('phonepay', 'PhonePay'), ('card', 'Card')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=10)),
                ('merchant_id', models.TextField(blank=True)),
                ('public_key', models.TextField(blank=True)),
                ('secret_key', models.TextField(blank=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hotel', 'gateway_type')},
            },
        ),
    ]
