# Generated by Django 6.0.3 on 2026-04-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fix_phone_number_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeping',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='toiletries_restocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housekeeping',
            name='status',
            field=models.CharField(choices=[('in-progress', 'Cleaning in Progress'), ('ready', 'Ready'), ('need-cleaning', 'Need Cleaning'), ('inspecting', 'Inspecting')], default='need-cleaning', max_length=20),
        ),
    ]
