# Generated by Django 6.0.3 on 2026-04-07 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_housekeeping_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=20)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hk_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='LinenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linen_type', models.CharField(choices=[('towel', 'Towel'), ('bedsheet', 'Bedsheet'), ('pillow_cover', 'Pillow Cover'), ('duvet', 'Duvet Cover'), ('bathmat', 'Bath Mat')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_use', 'In Use'), ('washed', 'Washed'), ('damaged', 'Damaged'), ('disposed', 'Disposed')], default='in_use', max_length=20)),
                ('room_id', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linen_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['linen_type', 'status'],
            },
        ),
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('found_date', models.DateField()),
                ('found_by', models.CharField(blank=True, default='', max_length=100)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('found', 'Found'), ('claimed', 'Claimed'), ('disposed', 'Disposed')], default='found', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-found_date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('request_type', models.CharField(choices=[('extra_bed', 'Extra Bed'), ('baby_crib', 'Baby Crib'), ('cleaning', 'Cleaning'), ('towels', 'Extra Towels'), ('amenities', 'Amenities'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
