# Generated by Django 6.0.3 on 2026-04-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_housekeeping_extended_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontDeskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('notif_type', models.CharField(choices=[('room_ready', 'Room Ready'), ('special_request', 'Special Request'), ('guest_preference', 'Guest Preference Update'), ('general', 'General')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('preferences', models.TextField(blank=True, default='')),
                ('extra_bed', models.BooleanField(default=False)),
                ('baby_crib', models.BooleanField(default=False)),
                ('late_checkout', models.BooleanField(default=False)),
                ('early_checkin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='myapp.booking')),
            ],
        ),
    ]
