# Generated by Django 6.0.3 on 2026-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_hk_inventory_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='usage_type',
            field=models.CharField(choices=[('general', 'General'), ('housekeeping', 'Housekeeping'), ('order', 'Order / Kitchen'), ('both', 'Both (Housekeeping & Orders)')], default='general', max_length=20),
        ),
    ]
