# Generated by Django 6.0.3 on 2026-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_inventory_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
