# Generated by Django 6.0.3 on 2026-04-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_booking_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrequest',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_requests', to='myapp.booking'),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
