# Generated by Django 6.0.3 on 2026-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_specialrequest_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linenrecord',
            name='linen_type',
            field=models.CharField(max_length=100),
        ),
    ]
