# Generated by Django 6.0.3 on 2026-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_linen_type_freetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linenrecord',
            name='status',
            field=models.CharField(choices=[('in_use', 'In Use'), ('dirty', 'Dirty'), ('washing', 'Washing'), ('washed', 'Washed / Clean'), ('damaged', 'Damaged'), ('disposed', 'Disposed')], default='in_use', max_length=20),
        ),
    ]
