# Generated by Django 6.0.3 on 2026-05-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
